name: ImageSync

on:
  # enable manual runs
  workflow_dispatch:
  # enable Minimus Actions to trigger
  repository_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: "actions/checkout@v3"

    - name: Create config
      env:
        MINIMUS_TOKEN: ${{ secrets.MINIMUS_TOKEN  }}
      uses: cuchi/jinja2-action@v1.3.0
      with:
        template: skopeo_config.yaml.j2
        output_file: skopeo_config.yaml

    - run: cat skopeo_config.yaml
    
    - name: Sync
      run: |
        skopeo login -u GHCR_USER -p $GHCR_PASS $GHCR_REGISTRY &&
        skopeo sync --src yaml --dest docker --scoped \
        --override-arch amd64 \
        skopeo_config.yaml \
        $GHCR_REGISTRY
      env:
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
        GHCR_REGISTRY: "ghcr.io/readonlyrecords"
