# This is a basic workflow that is manually triggered

name: ImageSync

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: "Checkout"
        uses: "actions/checkout@v3"
        
    - name: Install skopeo
      run: |
        sudo apt-get -y update
        sudo apt-get -y install skopeo

    - name: Create config
      env:
        MINIMUS_TOKEN: ${{ secrets.MINIMUS_TOKEN  }}
      uses: cuchi/jinja2-action@v1.3.0
      with:
        template: skopeo_config.yaml.j2
        output_file: skopeo_config.yaml

    - run: cat skopeo_config.yaml
    
    - name: Sync
      run: |
        skopeo sync --src yaml --dest docker --scoped \
        --override-arch amd64 \
        skopeo_config.yaml \
        https://ghcr.io/readonlyrecords
